pipeline:
  build:
    image: gradle:5.4.1-jdk8
    secrets: [ drill_username, drill_password ]
    environment:
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - echo $${DRILL_USERNAME}
